### ISSUE TITLE
Download link

### ISSUE THREAD

**Issue by ewheeler** [unhcr/Humanitarian-Font#4]
Currently, the download link on https://unhcr.github.io/Humanitarian-Font/ downloads a zip of the entire repository rather than just the font files. I think most users would expect to only download the font

**Comment by Edouard-Legoupil** [comment]
Done !! https://github.com/unhcr/Humanitarian-Font/commit/09e5311d1a6729dad930db7bb1ee28e95cbf2bcf 

Thanks!

**Comment by ewheeler** [comment]
Great! Thx
