### ISSUE TITLE
UNICEF

### ISSUE THREAD

**Issue by ewheeler** [unhcr/Humanitarian-Font#5]
Label for the UNICEF icon incorrectly shows the name as `United Nations International Children's Emergency Fund`

UNICEF's name was changed in 1953 to `United Nations Children's Fund` though it kept the original acronym (see http://www.unicef.org/about/who/index_faq.html)

**Comment by Edouard-Legoupil** [comment]
Done https://github.com/unhcr/Humanitarian-Font/commit/80fafdafb5131fc4cc78455ed0920a797415ebb7 
Thanks

**Comment by ewheeler** [comment]
Wow that was fast! :)
Thanks!
